# Generated by Django 5.2 on 2025-04-29 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Requestee', 'Requestee'), ('Worker', 'Worker')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('Garbage Collection', 'Garbage Collection'), ('Water Leakage', 'Water Leakage'), ('Washroom Cleaning', 'Washroom Cleaning'), ('Electricity Issue', 'Electricity Issue')], max_length=50, null=True)),
                ('average_rating', models.FloatField(blank=True, default=None, null=True)),
                ('is_busy', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WasteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Garbage Collection', 'Garbage Collection'), ('Water Leakage', 'Water Leakage'), ('Washroom Cleaning', 'Washroom Cleaning'), ('Electricity Issue', 'Electricity Issue')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('request_image', models.ImageField(upload_to='request_images/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Pending Approval', 'Pending Approval'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completion_image', models.ImageField(blank=True, null=True, upload_to='completion_images/')),
                ('is_approved_by_student', models.BooleanField(default=False)),
                ('worker_rating', models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_worker', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'Worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('requestee', models.ForeignKey(limit_choices_to={'profile__role': 'Requestee'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
